### ISSUE TITLE
Openwrt 

### ISSUE THREAD

**Issue by paupong** [ganehag/open-modbusgateway#3]
Hi ,
      I am newbie,
      Howto compile in package of openwrt?
I just copy file in dir openwrt to .. and then make. It asked for mosquitto > 1.4.     But i have 1.5.9.   I tried todisable check but cannot

pop k

**Comment by ganehag** [comment]
I will try to come up with a descriptive way of how to do an in-tree compilation in a couple of days.

**Comment by ganehag** [comment]
I've now added a [section](https://github.com/ganehag/open-modbusgateway?tab=readme-ov-file#building-the-package-with-openwrt) to the README about how to use OpenWRT to build a package file.
